{{- $apps := mustMergeOverwrite .Values.commonApps .Values.additionalApps }}
{{- range $key, $val := $apps }}
{{- if .enable }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argo-cd
spec:
  project: {{ default "devops" .appProject }}
  {{- if .additionalValuesSourceRepos }}
  sources:
  - repoURL: {{ default "" .repoUrl }}
    targetRevision: {{ default "HEAD" .appTargetRevision }}
    path: k8s/{{ default $key .helmChartPath }}/
    helm:
      releaseName: {{ default $key .helmReleaseName }}
      skipCrds: {{ default false .helmSkipCrds }}
      valueFiles:
      - secrets://values.yaml
      {{- if ne .helmCustomValues false }}
      - secrets://values-{{ $.Values.env }}{{- if .helmCustomValuesSuffix }}-{{ .helmCustomValuesSuffix }}{{- end }}.yaml
      {{- range $additionalValuesSourceRepos := .additionalValuesSourceRepos }}
      - ${{ $additionalValuesSourceRepos.name }}/k8s/{{ default $key .helmChartPath }}/values-{{ $.Values.env }}{{- if .helmCustomValuesSuffix }}-{{ .helmCustomValuesSuffix }}{{- end }}.yaml
      {{- end }}
      {{- end }}
    {{- range $additionalValuesSourceRepos := .additionalValuesSourceRepos }}
  - repoURL: {{ $additionalValuesSourceRepos.repoUrl }}
    targetRevision: {{ default "HEAD" .appTargetRevision }}
    ref: {{ $additionalValuesSourceRepos.name }}
    {{- end }}
  {{- end }}
  source:
    repoURL: {{ default "" .repoUrl }}
    targetRevision: {{ default "HEAD" .appTargetRevision }}
    path: {{ default "k8s/" .helmChartPathPrefix }}{{ default $key .helmChartPath }}/
    helm:
      releaseName: {{ default $key .helmReleaseName }}
      {{- if .helmSkipCrds }}
      skipCrds: true
      {{- end }}
      valueFiles:
      - secrets://values.yaml
      {{- if ne .helmCustomValues false }}
      - secrets://values-{{ $.Values.env }}{{- if .helmCustomValuesSuffix }}-{{ .helmCustomValuesSuffix }}{{- end }}.yaml
      {{- end }}
  destination:
    {{- if .targetClusterName }}
    name: {{ .targetClusterName }}
    {{- else }}
    server: {{ default "https://kubernetes.default.svc" .targetClusterURL }}
    {{- end }}
    namespace: {{ default $key .helmReleaseNamespace }}
  syncPolicy:
    {{- if ne .autosync false }}
    automated:
      selfHeal: true
      prune: true
    {{- end }}
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - FailOnSharedResource=true
    {{- if .helmSyncOptionsReplace }}
    - Replace=true
    {{- end }}
    {{- if .appIgnoreDifferences }}
    - RespectIgnoreDifferences=true
    {{- end }}
    {{- if .appServerSideApply }}
    - ServerSideApply=true
    {{- end }}
    retry:
      limit: 3
  {{- if .appIgnoreDifferences }}
  ignoreDifferences: {{ toYaml .appIgnoreDifferences | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
