// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * Repository is the Schema for the Repositorys API. Provides an Elastic Container Registry Repository.
Deprecated: This API version (v1beta1) has been deprecated in release v2.6.0.
 *
 * @schema Repository
 */
export class Repository extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Repository"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'ecr.aws.upbound.io/v1beta1',
    kind: 'Repository',
  }

  /**
   * Renders a Kubernetes manifest for "Repository".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: RepositoryProps): any {
    return {
      ...Repository.GVK,
      ...toJson_RepositoryProps(props),
    };
  }

  /**
   * Defines a "Repository" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: RepositoryProps) {
    super(scope, id, {
      ...Repository.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...Repository.GVK,
      ...toJson_RepositoryProps(resolved),
    };
  }
}

/**
 * Repository is the Schema for the Repositorys API. Provides an Elastic Container Registry Repository.
 * Deprecated: This API version (v1beta1) has been deprecated in release v2.6.0.
 *
 * @schema Repository
 */
export interface RepositoryProps {
  /**
   * @schema Repository#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * RepositorySpec defines the desired state of Repository
   *
   * @schema Repository#spec
   */
  readonly spec: RepositorySpec;
}

/**
 * Converts an object of type 'RepositoryProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryProps(obj: RepositoryProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_RepositorySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * RepositorySpec defines the desired state of Repository
 *
 * @schema RepositorySpec
 */
export interface RepositorySpec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external
   * when this managed resource is deleted - either "Delete" or "Orphan" the
   * external resource.
   * This field is planned to be deprecated in favor of the ManagementPolicies
   * field in a future release. Currently, both could be set independently and
   * non-default values would be honored if the feature flag is enabled.
   * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
   *
   * @schema RepositorySpec#deletionPolicy
   */
  readonly deletionPolicy?: RepositorySpecDeletionPolicy;

  /**
   * @schema RepositorySpec#forProvider
   */
  readonly forProvider: RepositorySpecForProvider;

  /**
   * THIS IS A BETA FIELD. It will be honored
   * unless the Management Policies feature flag is disabled.
   * InitProvider holds the same fields as ForProvider, with the exception
   * of Identifier and other resource reference fields. The fields that are
   * in InitProvider are merged into ForProvider when the resource is created.
   * The same fields are also added to the terraform ignore_changes hook, to
   * avoid updating them after creation. This is useful for fields that are
   * required on creation, but we do not desire to update them after creation,
   * for example because of an external controller is managing them, like an
   * autoscaler.
   *
   * @schema RepositorySpec#initProvider
   */
  readonly initProvider?: RepositorySpecInitProvider;

  /**
   * THIS IS A BETA FIELD. It is on by default but can be opted out
   * through a Crossplane feature flag.
   * ManagementPolicies specify the array of actions Crossplane is allowed to
   * take on the managed and external resources.
   * This field is planned to replace the DeletionPolicy field in a future
   * release. Currently, both could be set independently and non-default
   * values would be honored if the feature flag is enabled. If both are
   * custom, the DeletionPolicy field will be ignored.
   * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
   * and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
   *
   * @schema RepositorySpec#managementPolicies
   */
  readonly managementPolicies?: RepositorySpecManagementPolicies[];

  /**
   * ProviderConfigReference specifies how the provider that will be used to
   * create, observe, update, and delete this managed resource should be
   * configured.
   *
   * @schema RepositorySpec#providerConfigRef
   */
  readonly providerConfigRef?: RepositorySpecProviderConfigRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a
   * Secret to which any connection details for this managed resource should
   * be written. Connection details frequently include the endpoint, username,
   * and password required to connect to the managed resource.
   *
   * @schema RepositorySpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: RepositorySpecWriteConnectionSecretToRef;
}

/**
 * Converts an object of type 'RepositorySpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpec(obj: RepositorySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'deletionPolicy': obj.deletionPolicy,
    'forProvider': toJson_RepositorySpecForProvider(obj.forProvider),
    'initProvider': toJson_RepositorySpecInitProvider(obj.initProvider),
    'managementPolicies': obj.managementPolicies?.map(y => y),
    'providerConfigRef': toJson_RepositorySpecProviderConfigRef(obj.providerConfigRef),
    'writeConnectionSecretToRef': toJson_RepositorySpecWriteConnectionSecretToRef(obj.writeConnectionSecretToRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * DeletionPolicy specifies what will happen to the underlying external
 * when this managed resource is deleted - either "Delete" or "Orphan" the
 * external resource.
 * This field is planned to be deprecated in favor of the ManagementPolicies
 * field in a future release. Currently, both could be set independently and
 * non-default values would be honored if the feature flag is enabled.
 * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
 *
 * @schema RepositorySpecDeletionPolicy
 */
export enum RepositorySpecDeletionPolicy {
  /** Orphan */
  ORPHAN = "Orphan",
  /** Delete */
  DELETE = "Delete",
}

/**
 * @schema RepositorySpecForProvider
 */
export interface RepositorySpecForProvider {
  /**
   * Encryption configuration for the repository. See below for schema.
   *
   * @schema RepositorySpecForProvider#encryptionConfiguration
   */
  readonly encryptionConfiguration?: RepositorySpecForProviderEncryptionConfiguration[];

  /**
   * If true, will delete the repository even if it contains images.
   * Defaults to false.
   *
   * @default false.
   * @schema RepositorySpecForProvider#forceDelete
   */
  readonly forceDelete?: boolean;

  /**
   * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
   *
   * @schema RepositorySpecForProvider#imageScanningConfiguration
   */
  readonly imageScanningConfiguration?: RepositorySpecForProviderImageScanningConfiguration[];

  /**
   * The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE.
   *
   * @default MUTABLE.
   * @schema RepositorySpecForProvider#imageTagMutability
   */
  readonly imageTagMutability?: string;

  /**
   * Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema.
   *
   * @schema RepositorySpecForProvider#imageTagMutabilityExclusionFilter
   */
  readonly imageTagMutabilityExclusionFilter?: RepositorySpecForProviderImageTagMutabilityExclusionFilter[];

  /**
   * Region where this resource will be managed. Defaults to the Region set in the provider configuration.
   * Region is the region you'd like your resource to be created in.
   *
   * @default the Region set in the provider configuration.
   * @schema RepositorySpecForProvider#region
   */
  readonly region: string;

  /**
   * Key-value map of resource tags.
   *
   * @schema RepositorySpecForProvider#tags
   */
  readonly tags?: { [key: string]: string };
}

/**
 * Converts an object of type 'RepositorySpecForProvider' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProvider(obj: RepositorySpecForProvider | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionConfiguration': obj.encryptionConfiguration?.map(y => toJson_RepositorySpecForProviderEncryptionConfiguration(y)),
    'forceDelete': obj.forceDelete,
    'imageScanningConfiguration': obj.imageScanningConfiguration?.map(y => toJson_RepositorySpecForProviderImageScanningConfiguration(y)),
    'imageTagMutability': obj.imageTagMutability,
    'imageTagMutabilityExclusionFilter': obj.imageTagMutabilityExclusionFilter?.map(y => toJson_RepositorySpecForProviderImageTagMutabilityExclusionFilter(y)),
    'region': obj.region,
    'tags': ((obj.tags) === undefined) ? undefined : (Object.entries(obj.tags).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * THIS IS A BETA FIELD. It will be honored
 * unless the Management Policies feature flag is disabled.
 * InitProvider holds the same fields as ForProvider, with the exception
 * of Identifier and other resource reference fields. The fields that are
 * in InitProvider are merged into ForProvider when the resource is created.
 * The same fields are also added to the terraform ignore_changes hook, to
 * avoid updating them after creation. This is useful for fields that are
 * required on creation, but we do not desire to update them after creation,
 * for example because of an external controller is managing them, like an
 * autoscaler.
 *
 * @schema RepositorySpecInitProvider
 */
export interface RepositorySpecInitProvider {
  /**
   * Encryption configuration for the repository. See below for schema.
   *
   * @schema RepositorySpecInitProvider#encryptionConfiguration
   */
  readonly encryptionConfiguration?: RepositorySpecInitProviderEncryptionConfiguration[];

  /**
   * If true, will delete the repository even if it contains images.
   * Defaults to false.
   *
   * @default false.
   * @schema RepositorySpecInitProvider#forceDelete
   */
  readonly forceDelete?: boolean;

  /**
   * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
   *
   * @schema RepositorySpecInitProvider#imageScanningConfiguration
   */
  readonly imageScanningConfiguration?: RepositorySpecInitProviderImageScanningConfiguration[];

  /**
   * The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE.
   *
   * @default MUTABLE.
   * @schema RepositorySpecInitProvider#imageTagMutability
   */
  readonly imageTagMutability?: string;

  /**
   * Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema.
   *
   * @schema RepositorySpecInitProvider#imageTagMutabilityExclusionFilter
   */
  readonly imageTagMutabilityExclusionFilter?: RepositorySpecInitProviderImageTagMutabilityExclusionFilter[];

  /**
   * Key-value map of resource tags.
   *
   * @schema RepositorySpecInitProvider#tags
   */
  readonly tags?: { [key: string]: string };
}

/**
 * Converts an object of type 'RepositorySpecInitProvider' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProvider(obj: RepositorySpecInitProvider | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionConfiguration': obj.encryptionConfiguration?.map(y => toJson_RepositorySpecInitProviderEncryptionConfiguration(y)),
    'forceDelete': obj.forceDelete,
    'imageScanningConfiguration': obj.imageScanningConfiguration?.map(y => toJson_RepositorySpecInitProviderImageScanningConfiguration(y)),
    'imageTagMutability': obj.imageTagMutability,
    'imageTagMutabilityExclusionFilter': obj.imageTagMutabilityExclusionFilter?.map(y => toJson_RepositorySpecInitProviderImageTagMutabilityExclusionFilter(y)),
    'tags': ((obj.tags) === undefined) ? undefined : (Object.entries(obj.tags).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * A ManagementAction represents an action that the Crossplane controllers
 * can take on an external resource.
 *
 * @schema RepositorySpecManagementPolicies
 */
export enum RepositorySpecManagementPolicies {
  /** Observe */
  OBSERVE = "Observe",
  /** Create */
  CREATE = "Create",
  /** Update */
  UPDATE = "Update",
  /** Delete */
  DELETE = "Delete",
  /** LateInitialize */
  LATE_INITIALIZE = "LateInitialize",
  /** * */
  VALUE_ASTERISK = "*",
}

/**
 * ProviderConfigReference specifies how the provider that will be used to
 * create, observe, update, and delete this managed resource should be
 * configured.
 *
 * @schema RepositorySpecProviderConfigRef
 */
export interface RepositorySpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositorySpecProviderConfigRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositorySpecProviderConfigRef#policy
   */
  readonly policy?: RepositorySpecProviderConfigRefPolicy;
}

/**
 * Converts an object of type 'RepositorySpecProviderConfigRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecProviderConfigRef(obj: RepositorySpecProviderConfigRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositorySpecProviderConfigRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a
 * Secret to which any connection details for this managed resource should
 * be written. Connection details frequently include the endpoint, username,
 * and password required to connect to the managed resource.
 *
 * @schema RepositorySpecWriteConnectionSecretToRef
 */
export interface RepositorySpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema RepositorySpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema RepositorySpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;
}

/**
 * Converts an object of type 'RepositorySpecWriteConnectionSecretToRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecWriteConnectionSecretToRef(obj: RepositorySpecWriteConnectionSecretToRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecForProviderEncryptionConfiguration
 */
export interface RepositorySpecForProviderEncryptionConfiguration {
  /**
   * The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256.
   *
   * @default AES256.
   * @schema RepositorySpecForProviderEncryptionConfiguration#encryptionType
   */
  readonly encryptionType?: string;

  /**
   * The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR.
   *
   * @schema RepositorySpecForProviderEncryptionConfiguration#kmsKey
   */
  readonly kmsKey?: string;

  /**
   * Reference to a Key in kms to populate kmsKey.
   *
   * @schema RepositorySpecForProviderEncryptionConfiguration#kmsKeyRef
   */
  readonly kmsKeyRef?: RepositorySpecForProviderEncryptionConfigurationKmsKeyRef;

  /**
   * Selector for a Key in kms to populate kmsKey.
   *
   * @schema RepositorySpecForProviderEncryptionConfiguration#kmsKeySelector
   */
  readonly kmsKeySelector?: RepositorySpecForProviderEncryptionConfigurationKmsKeySelector;
}

/**
 * Converts an object of type 'RepositorySpecForProviderEncryptionConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderEncryptionConfiguration(obj: RepositorySpecForProviderEncryptionConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionType': obj.encryptionType,
    'kmsKey': obj.kmsKey,
    'kmsKeyRef': toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeyRef(obj.kmsKeyRef),
    'kmsKeySelector': toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeySelector(obj.kmsKeySelector),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecForProviderImageScanningConfiguration
 */
export interface RepositorySpecForProviderImageScanningConfiguration {
  /**
   * Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).
   *
   * @schema RepositorySpecForProviderImageScanningConfiguration#scanOnPush
   */
  readonly scanOnPush?: boolean;
}

/**
 * Converts an object of type 'RepositorySpecForProviderImageScanningConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderImageScanningConfiguration(obj: RepositorySpecForProviderImageScanningConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'scanOnPush': obj.scanOnPush,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecForProviderImageTagMutabilityExclusionFilter
 */
export interface RepositorySpecForProviderImageTagMutabilityExclusionFilter {
  /**
   * The filter pattern to use for excluding image tags from the mutability setting. Must contain only letters, numbers, and special characters (._-). Each filter can be up to 128 characters long and can contain a maximum of 2 wildcards ().
   *
   * @schema RepositorySpecForProviderImageTagMutabilityExclusionFilter#filter
   */
  readonly filter?: string;

  /**
   * The type of filter to use. Must be WILDCARD.
   *
   * @schema RepositorySpecForProviderImageTagMutabilityExclusionFilter#filterType
   */
  readonly filterType?: string;
}

/**
 * Converts an object of type 'RepositorySpecForProviderImageTagMutabilityExclusionFilter' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderImageTagMutabilityExclusionFilter(obj: RepositorySpecForProviderImageTagMutabilityExclusionFilter | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'filter': obj.filter,
    'filterType': obj.filterType,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecInitProviderEncryptionConfiguration
 */
export interface RepositorySpecInitProviderEncryptionConfiguration {
  /**
   * The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256.
   *
   * @default AES256.
   * @schema RepositorySpecInitProviderEncryptionConfiguration#encryptionType
   */
  readonly encryptionType?: string;

  /**
   * The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR.
   *
   * @schema RepositorySpecInitProviderEncryptionConfiguration#kmsKey
   */
  readonly kmsKey?: string;

  /**
   * Reference to a Key in kms to populate kmsKey.
   *
   * @schema RepositorySpecInitProviderEncryptionConfiguration#kmsKeyRef
   */
  readonly kmsKeyRef?: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef;

  /**
   * Selector for a Key in kms to populate kmsKey.
   *
   * @schema RepositorySpecInitProviderEncryptionConfiguration#kmsKeySelector
   */
  readonly kmsKeySelector?: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderEncryptionConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderEncryptionConfiguration(obj: RepositorySpecInitProviderEncryptionConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionType': obj.encryptionType,
    'kmsKey': obj.kmsKey,
    'kmsKeyRef': toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef(obj.kmsKeyRef),
    'kmsKeySelector': toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector(obj.kmsKeySelector),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecInitProviderImageScanningConfiguration
 */
export interface RepositorySpecInitProviderImageScanningConfiguration {
  /**
   * Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).
   *
   * @schema RepositorySpecInitProviderImageScanningConfiguration#scanOnPush
   */
  readonly scanOnPush?: boolean;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderImageScanningConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderImageScanningConfiguration(obj: RepositorySpecInitProviderImageScanningConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'scanOnPush': obj.scanOnPush,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositorySpecInitProviderImageTagMutabilityExclusionFilter
 */
export interface RepositorySpecInitProviderImageTagMutabilityExclusionFilter {
  /**
   * The filter pattern to use for excluding image tags from the mutability setting. Must contain only letters, numbers, and special characters (._-). Each filter can be up to 128 characters long and can contain a maximum of 2 wildcards ().
   *
   * @schema RepositorySpecInitProviderImageTagMutabilityExclusionFilter#filter
   */
  readonly filter?: string;

  /**
   * The type of filter to use. Must be WILDCARD.
   *
   * @schema RepositorySpecInitProviderImageTagMutabilityExclusionFilter#filterType
   */
  readonly filterType?: string;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderImageTagMutabilityExclusionFilter' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderImageTagMutabilityExclusionFilter(obj: RepositorySpecInitProviderImageTagMutabilityExclusionFilter | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'filter': obj.filter,
    'filterType': obj.filterType,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for referencing.
 *
 * @schema RepositorySpecProviderConfigRefPolicy
 */
export interface RepositorySpecProviderConfigRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositorySpecProviderConfigRefPolicy#resolution
   */
  readonly resolution?: RepositorySpecProviderConfigRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositorySpecProviderConfigRefPolicy#resolve
   */
  readonly resolve?: RepositorySpecProviderConfigRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositorySpecProviderConfigRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecProviderConfigRefPolicy(obj: RepositorySpecProviderConfigRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a Key in kms to populate kmsKey.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRef
 */
export interface RepositorySpecForProviderEncryptionConfigurationKmsKeyRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRef#policy
   */
  readonly policy?: RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy;
}

/**
 * Converts an object of type 'RepositorySpecForProviderEncryptionConfigurationKmsKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeyRef(obj: RepositorySpecForProviderEncryptionConfigurationKmsKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selector for a Key in kms to populate kmsKey.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelector
 */
export interface RepositorySpecForProviderEncryptionConfigurationKmsKeySelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference
   * as the selecting object is selected.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

  /**
   * Policies for selection.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelector#policy
   */
  readonly policy?: RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy;
}

/**
 * Converts an object of type 'RepositorySpecForProviderEncryptionConfigurationKmsKeySelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeySelector(obj: RepositorySpecForProviderEncryptionConfigurationKmsKeySelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchControllerRef': obj.matchControllerRef,
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'policy': toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a Key in kms to populate kmsKey.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef
 */
export interface RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef#policy
   */
  readonly policy?: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef(obj: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selector for a Key in kms to populate kmsKey.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector
 */
export interface RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference
   * as the selecting object is selected.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

  /**
   * Policies for selection.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector#policy
   */
  readonly policy?: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector(obj: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchControllerRef': obj.matchControllerRef,
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'policy': toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositorySpecProviderConfigRefPolicyResolution
 */
export enum RepositorySpecProviderConfigRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositorySpecProviderConfigRefPolicyResolve
 */
export enum RepositorySpecProviderConfigRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Policies for referencing.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy
 */
export interface RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy#resolution
   */
  readonly resolution?: RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy#resolve
   */
  readonly resolve?: RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy(obj: RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for selection.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy
 */
export interface RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy#resolution
   */
  readonly resolution?: RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy#resolve
   */
  readonly resolve?: RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve;
}

/**
 * Converts an object of type 'RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy(obj: RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for referencing.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy
 */
export interface RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy#resolution
   */
  readonly resolution?: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy#resolve
   */
  readonly resolve?: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy(obj: RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for selection.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy
 */
export interface RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy#resolution
   */
  readonly resolution?: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy#resolve
   */
  readonly resolve?: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve;
}

/**
 * Converts an object of type 'RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy(obj: RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution
 */
export enum RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve
 */
export enum RepositorySpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution
 */
export enum RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve
 */
export enum RepositorySpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution
 */
export enum RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve
 */
export enum RepositorySpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution
 */
export enum RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve
 */
export enum RepositorySpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}


/**
 * Repository is the Schema for the Repositorys API. Provides an Elastic Container Registry Repository.
 *
 * @schema RepositoryV1Beta2
 */
export class RepositoryV1Beta2 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "RepositoryV1Beta2"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'ecr.aws.upbound.io/v1beta2',
    kind: 'Repository',
  }

  /**
   * Renders a Kubernetes manifest for "RepositoryV1Beta2".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: RepositoryV1Beta2Props): any {
    return {
      ...RepositoryV1Beta2.GVK,
      ...toJson_RepositoryV1Beta2Props(props),
    };
  }

  /**
   * Defines a "RepositoryV1Beta2" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: RepositoryV1Beta2Props) {
    super(scope, id, {
      ...RepositoryV1Beta2.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...RepositoryV1Beta2.GVK,
      ...toJson_RepositoryV1Beta2Props(resolved),
    };
  }
}

/**
 * Repository is the Schema for the Repositorys API. Provides an Elastic Container Registry Repository.
 *
 * @schema RepositoryV1Beta2
 */
export interface RepositoryV1Beta2Props {
  /**
   * @schema RepositoryV1Beta2#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * RepositorySpec defines the desired state of Repository
   *
   * @schema RepositoryV1Beta2#spec
   */
  readonly spec: RepositoryV1Beta2Spec;
}

/**
 * Converts an object of type 'RepositoryV1Beta2Props' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2Props(obj: RepositoryV1Beta2Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_RepositoryV1Beta2Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * RepositorySpec defines the desired state of Repository
 *
 * @schema RepositoryV1Beta2Spec
 */
export interface RepositoryV1Beta2Spec {
  /**
   * DeletionPolicy specifies what will happen to the underlying external
   * when this managed resource is deleted - either "Delete" or "Orphan" the
   * external resource.
   * This field is planned to be deprecated in favor of the ManagementPolicies
   * field in a future release. Currently, both could be set independently and
   * non-default values would be honored if the feature flag is enabled.
   * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
   *
   * @schema RepositoryV1Beta2Spec#deletionPolicy
   */
  readonly deletionPolicy?: RepositoryV1Beta2SpecDeletionPolicy;

  /**
   * @schema RepositoryV1Beta2Spec#forProvider
   */
  readonly forProvider: RepositoryV1Beta2SpecForProvider;

  /**
   * THIS IS A BETA FIELD. It will be honored
   * unless the Management Policies feature flag is disabled.
   * InitProvider holds the same fields as ForProvider, with the exception
   * of Identifier and other resource reference fields. The fields that are
   * in InitProvider are merged into ForProvider when the resource is created.
   * The same fields are also added to the terraform ignore_changes hook, to
   * avoid updating them after creation. This is useful for fields that are
   * required on creation, but we do not desire to update them after creation,
   * for example because of an external controller is managing them, like an
   * autoscaler.
   *
   * @schema RepositoryV1Beta2Spec#initProvider
   */
  readonly initProvider?: RepositoryV1Beta2SpecInitProvider;

  /**
   * THIS IS A BETA FIELD. It is on by default but can be opted out
   * through a Crossplane feature flag.
   * ManagementPolicies specify the array of actions Crossplane is allowed to
   * take on the managed and external resources.
   * This field is planned to replace the DeletionPolicy field in a future
   * release. Currently, both could be set independently and non-default
   * values would be honored if the feature flag is enabled. If both are
   * custom, the DeletionPolicy field will be ignored.
   * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
   * and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
   *
   * @schema RepositoryV1Beta2Spec#managementPolicies
   */
  readonly managementPolicies?: RepositoryV1Beta2SpecManagementPolicies[];

  /**
   * ProviderConfigReference specifies how the provider that will be used to
   * create, observe, update, and delete this managed resource should be
   * configured.
   *
   * @schema RepositoryV1Beta2Spec#providerConfigRef
   */
  readonly providerConfigRef?: RepositoryV1Beta2SpecProviderConfigRef;

  /**
   * WriteConnectionSecretToReference specifies the namespace and name of a
   * Secret to which any connection details for this managed resource should
   * be written. Connection details frequently include the endpoint, username,
   * and password required to connect to the managed resource.
   *
   * @schema RepositoryV1Beta2Spec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: RepositoryV1Beta2SpecWriteConnectionSecretToRef;
}

/**
 * Converts an object of type 'RepositoryV1Beta2Spec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2Spec(obj: RepositoryV1Beta2Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'deletionPolicy': obj.deletionPolicy,
    'forProvider': toJson_RepositoryV1Beta2SpecForProvider(obj.forProvider),
    'initProvider': toJson_RepositoryV1Beta2SpecInitProvider(obj.initProvider),
    'managementPolicies': obj.managementPolicies?.map(y => y),
    'providerConfigRef': toJson_RepositoryV1Beta2SpecProviderConfigRef(obj.providerConfigRef),
    'writeConnectionSecretToRef': toJson_RepositoryV1Beta2SpecWriteConnectionSecretToRef(obj.writeConnectionSecretToRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * DeletionPolicy specifies what will happen to the underlying external
 * when this managed resource is deleted - either "Delete" or "Orphan" the
 * external resource.
 * This field is planned to be deprecated in favor of the ManagementPolicies
 * field in a future release. Currently, both could be set independently and
 * non-default values would be honored if the feature flag is enabled.
 * See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
 *
 * @schema RepositoryV1Beta2SpecDeletionPolicy
 */
export enum RepositoryV1Beta2SpecDeletionPolicy {
  /** Orphan */
  ORPHAN = "Orphan",
  /** Delete */
  DELETE = "Delete",
}

/**
 * @schema RepositoryV1Beta2SpecForProvider
 */
export interface RepositoryV1Beta2SpecForProvider {
  /**
   * Encryption configuration for the repository. See below for schema.
   *
   * @schema RepositoryV1Beta2SpecForProvider#encryptionConfiguration
   */
  readonly encryptionConfiguration?: RepositoryV1Beta2SpecForProviderEncryptionConfiguration[];

  /**
   * If true, will delete the repository even if it contains images.
   * Defaults to false.
   *
   * @default false.
   * @schema RepositoryV1Beta2SpecForProvider#forceDelete
   */
  readonly forceDelete?: boolean;

  /**
   * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
   *
   * @schema RepositoryV1Beta2SpecForProvider#imageScanningConfiguration
   */
  readonly imageScanningConfiguration?: RepositoryV1Beta2SpecForProviderImageScanningConfiguration;

  /**
   * The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE.
   *
   * @default MUTABLE.
   * @schema RepositoryV1Beta2SpecForProvider#imageTagMutability
   */
  readonly imageTagMutability?: string;

  /**
   * Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema.
   *
   * @schema RepositoryV1Beta2SpecForProvider#imageTagMutabilityExclusionFilter
   */
  readonly imageTagMutabilityExclusionFilter?: RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter[];

  /**
   * Region where this resource will be managed. Defaults to the Region set in the provider configuration.
   * Region is the region you'd like your resource to be created in.
   *
   * @default the Region set in the provider configuration.
   * @schema RepositoryV1Beta2SpecForProvider#region
   */
  readonly region: string;

  /**
   * Key-value map of resource tags.
   *
   * @schema RepositoryV1Beta2SpecForProvider#tags
   */
  readonly tags?: { [key: string]: string };
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProvider' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProvider(obj: RepositoryV1Beta2SpecForProvider | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionConfiguration': obj.encryptionConfiguration?.map(y => toJson_RepositoryV1Beta2SpecForProviderEncryptionConfiguration(y)),
    'forceDelete': obj.forceDelete,
    'imageScanningConfiguration': toJson_RepositoryV1Beta2SpecForProviderImageScanningConfiguration(obj.imageScanningConfiguration),
    'imageTagMutability': obj.imageTagMutability,
    'imageTagMutabilityExclusionFilter': obj.imageTagMutabilityExclusionFilter?.map(y => toJson_RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter(y)),
    'region': obj.region,
    'tags': ((obj.tags) === undefined) ? undefined : (Object.entries(obj.tags).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * THIS IS A BETA FIELD. It will be honored
 * unless the Management Policies feature flag is disabled.
 * InitProvider holds the same fields as ForProvider, with the exception
 * of Identifier and other resource reference fields. The fields that are
 * in InitProvider are merged into ForProvider when the resource is created.
 * The same fields are also added to the terraform ignore_changes hook, to
 * avoid updating them after creation. This is useful for fields that are
 * required on creation, but we do not desire to update them after creation,
 * for example because of an external controller is managing them, like an
 * autoscaler.
 *
 * @schema RepositoryV1Beta2SpecInitProvider
 */
export interface RepositoryV1Beta2SpecInitProvider {
  /**
   * Encryption configuration for the repository. See below for schema.
   *
   * @schema RepositoryV1Beta2SpecInitProvider#encryptionConfiguration
   */
  readonly encryptionConfiguration?: RepositoryV1Beta2SpecInitProviderEncryptionConfiguration[];

  /**
   * If true, will delete the repository even if it contains images.
   * Defaults to false.
   *
   * @default false.
   * @schema RepositoryV1Beta2SpecInitProvider#forceDelete
   */
  readonly forceDelete?: boolean;

  /**
   * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
   *
   * @schema RepositoryV1Beta2SpecInitProvider#imageScanningConfiguration
   */
  readonly imageScanningConfiguration?: RepositoryV1Beta2SpecInitProviderImageScanningConfiguration;

  /**
   * The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE.
   *
   * @default MUTABLE.
   * @schema RepositoryV1Beta2SpecInitProvider#imageTagMutability
   */
  readonly imageTagMutability?: string;

  /**
   * Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema.
   *
   * @schema RepositoryV1Beta2SpecInitProvider#imageTagMutabilityExclusionFilter
   */
  readonly imageTagMutabilityExclusionFilter?: RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter[];

  /**
   * Key-value map of resource tags.
   *
   * @schema RepositoryV1Beta2SpecInitProvider#tags
   */
  readonly tags?: { [key: string]: string };
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProvider' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProvider(obj: RepositoryV1Beta2SpecInitProvider | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionConfiguration': obj.encryptionConfiguration?.map(y => toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfiguration(y)),
    'forceDelete': obj.forceDelete,
    'imageScanningConfiguration': toJson_RepositoryV1Beta2SpecInitProviderImageScanningConfiguration(obj.imageScanningConfiguration),
    'imageTagMutability': obj.imageTagMutability,
    'imageTagMutabilityExclusionFilter': obj.imageTagMutabilityExclusionFilter?.map(y => toJson_RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter(y)),
    'tags': ((obj.tags) === undefined) ? undefined : (Object.entries(obj.tags).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * A ManagementAction represents an action that the Crossplane controllers
 * can take on an external resource.
 *
 * @schema RepositoryV1Beta2SpecManagementPolicies
 */
export enum RepositoryV1Beta2SpecManagementPolicies {
  /** Observe */
  OBSERVE = "Observe",
  /** Create */
  CREATE = "Create",
  /** Update */
  UPDATE = "Update",
  /** Delete */
  DELETE = "Delete",
  /** LateInitialize */
  LATE_INITIALIZE = "LateInitialize",
  /** * */
  VALUE_ASTERISK = "*",
}

/**
 * ProviderConfigReference specifies how the provider that will be used to
 * create, observe, update, and delete this managed resource should be
 * configured.
 *
 * @schema RepositoryV1Beta2SpecProviderConfigRef
 */
export interface RepositoryV1Beta2SpecProviderConfigRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositoryV1Beta2SpecProviderConfigRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositoryV1Beta2SpecProviderConfigRef#policy
   */
  readonly policy?: RepositoryV1Beta2SpecProviderConfigRefPolicy;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecProviderConfigRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecProviderConfigRef(obj: RepositoryV1Beta2SpecProviderConfigRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositoryV1Beta2SpecProviderConfigRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * WriteConnectionSecretToReference specifies the namespace and name of a
 * Secret to which any connection details for this managed resource should
 * be written. Connection details frequently include the endpoint, username,
 * and password required to connect to the managed resource.
 *
 * @schema RepositoryV1Beta2SpecWriteConnectionSecretToRef
 */
export interface RepositoryV1Beta2SpecWriteConnectionSecretToRef {
  /**
   * Name of the secret.
   *
   * @schema RepositoryV1Beta2SpecWriteConnectionSecretToRef#name
   */
  readonly name: string;

  /**
   * Namespace of the secret.
   *
   * @schema RepositoryV1Beta2SpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace: string;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecWriteConnectionSecretToRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecWriteConnectionSecretToRef(obj: RepositoryV1Beta2SpecWriteConnectionSecretToRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfiguration
 */
export interface RepositoryV1Beta2SpecForProviderEncryptionConfiguration {
  /**
   * The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256.
   *
   * @default AES256.
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfiguration#encryptionType
   */
  readonly encryptionType?: string;

  /**
   * The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfiguration#kmsKey
   */
  readonly kmsKey?: string;

  /**
   * Reference to a Key in kms to populate kmsKey.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfiguration#kmsKeyRef
   */
  readonly kmsKeyRef?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef;

  /**
   * Selector for a Key in kms to populate kmsKey.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfiguration#kmsKeySelector
   */
  readonly kmsKeySelector?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderEncryptionConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderEncryptionConfiguration(obj: RepositoryV1Beta2SpecForProviderEncryptionConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionType': obj.encryptionType,
    'kmsKey': obj.kmsKey,
    'kmsKeyRef': toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef(obj.kmsKeyRef),
    'kmsKeySelector': toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector(obj.kmsKeySelector),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
 *
 * @schema RepositoryV1Beta2SpecForProviderImageScanningConfiguration
 */
export interface RepositoryV1Beta2SpecForProviderImageScanningConfiguration {
  /**
   * Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).
   *
   * @schema RepositoryV1Beta2SpecForProviderImageScanningConfiguration#scanOnPush
   */
  readonly scanOnPush?: boolean;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderImageScanningConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderImageScanningConfiguration(obj: RepositoryV1Beta2SpecForProviderImageScanningConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'scanOnPush': obj.scanOnPush,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter
 */
export interface RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter {
  /**
   * The filter pattern to use for excluding image tags from the mutability setting. Must contain only letters, numbers, and special characters (._-). Each filter can be up to 128 characters long and can contain a maximum of 2 wildcards ().
   *
   * @schema RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter#filter
   */
  readonly filter?: string;

  /**
   * The type of filter to use. Must be WILDCARD.
   *
   * @schema RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter#filterType
   */
  readonly filterType?: string;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter(obj: RepositoryV1Beta2SpecForProviderImageTagMutabilityExclusionFilter | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'filter': obj.filter,
    'filterType': obj.filterType,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfiguration
 */
export interface RepositoryV1Beta2SpecInitProviderEncryptionConfiguration {
  /**
   * The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256.
   *
   * @default AES256.
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfiguration#encryptionType
   */
  readonly encryptionType?: string;

  /**
   * The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfiguration#kmsKey
   */
  readonly kmsKey?: string;

  /**
   * Reference to a Key in kms to populate kmsKey.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfiguration#kmsKeyRef
   */
  readonly kmsKeyRef?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef;

  /**
   * Selector for a Key in kms to populate kmsKey.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfiguration#kmsKeySelector
   */
  readonly kmsKeySelector?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderEncryptionConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfiguration(obj: RepositoryV1Beta2SpecInitProviderEncryptionConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'encryptionType': obj.encryptionType,
    'kmsKey': obj.kmsKey,
    'kmsKeyRef': toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef(obj.kmsKeyRef),
    'kmsKeySelector': toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector(obj.kmsKeySelector),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning.
 *
 * @schema RepositoryV1Beta2SpecInitProviderImageScanningConfiguration
 */
export interface RepositoryV1Beta2SpecInitProviderImageScanningConfiguration {
  /**
   * Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false).
   *
   * @schema RepositoryV1Beta2SpecInitProviderImageScanningConfiguration#scanOnPush
   */
  readonly scanOnPush?: boolean;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderImageScanningConfiguration' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderImageScanningConfiguration(obj: RepositoryV1Beta2SpecInitProviderImageScanningConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'scanOnPush': obj.scanOnPush,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter
 */
export interface RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter {
  /**
   * The filter pattern to use for excluding image tags from the mutability setting. Must contain only letters, numbers, and special characters (._-). Each filter can be up to 128 characters long and can contain a maximum of 2 wildcards ().
   *
   * @schema RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter#filter
   */
  readonly filter?: string;

  /**
   * The type of filter to use. Must be WILDCARD.
   *
   * @schema RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter#filterType
   */
  readonly filterType?: string;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter(obj: RepositoryV1Beta2SpecInitProviderImageTagMutabilityExclusionFilter | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'filter': obj.filter,
    'filterType': obj.filterType,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for referencing.
 *
 * @schema RepositoryV1Beta2SpecProviderConfigRefPolicy
 */
export interface RepositoryV1Beta2SpecProviderConfigRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositoryV1Beta2SpecProviderConfigRefPolicy#resolution
   */
  readonly resolution?: RepositoryV1Beta2SpecProviderConfigRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositoryV1Beta2SpecProviderConfigRefPolicy#resolve
   */
  readonly resolve?: RepositoryV1Beta2SpecProviderConfigRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecProviderConfigRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecProviderConfigRefPolicy(obj: RepositoryV1Beta2SpecProviderConfigRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a Key in kms to populate kmsKey.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef
 */
export interface RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef#policy
   */
  readonly policy?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef(obj: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selector for a Key in kms to populate kmsKey.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector
 */
export interface RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference
   * as the selecting object is selected.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

  /**
   * Policies for selection.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector#policy
   */
  readonly policy?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector(obj: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchControllerRef': obj.matchControllerRef,
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'policy': toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a Key in kms to populate kmsKey.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef
 */
export interface RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef {
  /**
   * Name of the referenced object.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef#name
   */
  readonly name: string;

  /**
   * Policies for referencing.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef#policy
   */
  readonly policy?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef(obj: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'policy': toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selector for a Key in kms to populate kmsKey.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector
 */
export interface RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector {
  /**
   * MatchControllerRef ensures an object with the same controller reference
   * as the selecting object is selected.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector#matchControllerRef
   */
  readonly matchControllerRef?: boolean;

  /**
   * MatchLabels ensures an object with matching labels is selected.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

  /**
   * Policies for selection.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector#policy
   */
  readonly policy?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector(obj: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchControllerRef': obj.matchControllerRef,
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'policy': toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy(obj.policy),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositoryV1Beta2SpecProviderConfigRefPolicyResolution
 */
export enum RepositoryV1Beta2SpecProviderConfigRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositoryV1Beta2SpecProviderConfigRefPolicyResolve
 */
export enum RepositoryV1Beta2SpecProviderConfigRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Policies for referencing.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy
 */
export interface RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy#resolution
   */
  readonly resolution?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy#resolve
   */
  readonly resolve?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy(obj: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for selection.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy
 */
export interface RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy#resolution
   */
  readonly resolution?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy#resolve
   */
  readonly resolve?: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy(obj: RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for referencing.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy
 */
export interface RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy#resolution
   */
  readonly resolution?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy#resolve
   */
  readonly resolve?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy(obj: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Policies for selection.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy
 */
export interface RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy {
  /**
   * Resolution specifies whether resolution of this reference is required.
   * The default is 'Required', which means the reconcile will fail if the
   * reference cannot be resolved. 'Optional' means this reference will be
   * a no-op if it cannot be resolved.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy#resolution
   */
  readonly resolution?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution;

  /**
   * Resolve specifies when this reference should be resolved. The default
   * is 'IfNotPresent', which will attempt to resolve the reference only when
   * the corresponding field is not present. Use 'Always' to resolve the
   * reference on every reconcile.
   *
   * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy#resolve
   */
  readonly resolve?: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve;
}

/**
 * Converts an object of type 'RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy(obj: RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicy | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'resolution': obj.resolution,
    'resolve': obj.resolve,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution
 */
export enum RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve
 */
export enum RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeyRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution
 */
export enum RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve
 */
export enum RepositoryV1Beta2SpecForProviderEncryptionConfigurationKmsKeySelectorPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution
 */
export enum RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve
 */
export enum RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeyRefPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

/**
 * Resolution specifies whether resolution of this reference is required.
 * The default is 'Required', which means the reconcile will fail if the
 * reference cannot be resolved. 'Optional' means this reference will be
 * a no-op if it cannot be resolved.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution
 */
export enum RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolution {
  /** Required */
  REQUIRED = "Required",
  /** Optional */
  OPTIONAL = "Optional",
}

/**
 * Resolve specifies when this reference should be resolved. The default
 * is 'IfNotPresent', which will attempt to resolve the reference only when
 * the corresponding field is not present. Use 'Always' to resolve the
 * reference on every reconcile.
 *
 * @schema RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve
 */
export enum RepositoryV1Beta2SpecInitProviderEncryptionConfigurationKmsKeySelectorPolicyResolve {
  /** Always */
  ALWAYS = "Always",
  /** IfNotPresent */
  IF_NOT_PRESENT = "IfNotPresent",
}

