/**
 * CRD Imports - Re-export all generated CRD types
 *
 * Generated by cdk8s import, this file re-exports all CRDs
 * for convenient access via: import { ... } from 'nebula-cdk8s/imports';
 */

// ArgoCD native CRDs
export * as argoproj from "./argoproj.io";

// Crossplane core
export * as crossplane from "./pkg.crossplane.io";
export * as crossplaneExtensions from "./apiextensions.crossplane.io";

// Crossplane ArgoCD provider
export * as argocdProvider from "./argocd.crossplane.io";

// Crossplane GCP providers
export * as gcp from "./gcp.upbound.io";
export * as gcpCompute from "./compute.gcp.upbound.io";
export * as gcpContainer from "./container.gcp.upbound.io";
export * as gcpDns from "./dns.gcp.upbound.io";
export * as gcpStorage from "./storage.gcp.upbound.io";
export * as gcpCloudplatform from "./cloudplatform.gcp.upbound.io";

// Cert-Manager
export * as certManager from "./cert-manager.io";

// Prometheus/Monitoring
export * as monitoring from "./monitoring.coreos.com";

// Cluster API Core
export * as clusterApi from "./cluster.x-k8s.io";

// Cluster API Infrastructure Providers (GCP + k0smotron remote)
export * as capiInfra from "./infrastructure.cluster.x-k8s.io";

// k0smotron Control Plane Provider
export * as k0smotronControlPlane from "./controlplane.cluster.x-k8s.io";

// k0smotron Bootstrap Provider
export * as k0smotronBootstrap from "./bootstrap.cluster.x-k8s.io";

// k0smotron Core
export * as k0smotron from "./k0smotron.io";
