// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export type { ClusterArgs } from "./cluster";
import { Cluster } from "./cluster";
export { Cluster };

export type { ClusterListArgs } from "./clusterList";
import { ClusterList } from "./clusterList";
export { ClusterList };

export type { ClusterPatchArgs } from "./clusterPatch";
import { ClusterPatch } from "./clusterPatch";
export { ClusterPatch };


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:cluster.argocd.crossplane.io/v1alpha1:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "kubernetes:cluster.argocd.crossplane.io/v1alpha1:ClusterList":
                return new ClusterList(name, <any>undefined, { urn })
            case "kubernetes:cluster.argocd.crossplane.io/v1alpha1:ClusterPatch":
                return new ClusterPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "cluster.argocd.crossplane.io/v1alpha1", _module)
