// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export type { ProviderConfigArgs } from "./providerConfig";
import { ProviderConfig } from "./providerConfig";
export { ProviderConfig };

export type { ProviderConfigListArgs } from "./providerConfigList";
import { ProviderConfigList } from "./providerConfigList";
export { ProviderConfigList };

export type { ProviderConfigPatchArgs } from "./providerConfigPatch";
import { ProviderConfigPatch } from "./providerConfigPatch";
export { ProviderConfigPatch };


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:argocd.crossplane.io/v1alpha1:ProviderConfig":
                return new ProviderConfig(name, <any>undefined, { urn })
            case "kubernetes:argocd.crossplane.io/v1alpha1:ProviderConfigList":
                return new ProviderConfigList(name, <any>undefined, { urn })
            case "kubernetes:argocd.crossplane.io/v1alpha1:ProviderConfigPatch":
                return new ProviderConfigPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "argocd.crossplane.io/v1alpha1", _module)
