// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAttestation(args: GetAttestationArgs, opts?: pulumi.InvokeOptions): Promise<GetAttestationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellation:index/getAttestation:getAttestation", {
        "attestationVariant": args.attestationVariant,
        "csp": args.csp,
        "image": args.image,
        "insecure": args.insecure,
        "maaUrl": args.maaUrl,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAttestation.
 */
export interface GetAttestationArgs {
    attestationVariant: string;
    csp: string;
    image: inputs.GetAttestationImage;
    insecure?: boolean;
    maaUrl?: string;
}

/**
 * A collection of values returned by getAttestation.
 */
export interface GetAttestationResult {
    readonly attestation: outputs.GetAttestationAttestation;
    readonly attestationVariant: string;
    readonly csp: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly image: outputs.GetAttestationImage;
    readonly insecure?: boolean;
    readonly maaUrl?: string;
}
export function getAttestationOutput(args: GetAttestationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAttestationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellation:index/getAttestation:getAttestation", {
        "attestationVariant": args.attestationVariant,
        "csp": args.csp,
        "image": args.image,
        "insecure": args.insecure,
        "maaUrl": args.maaUrl,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAttestation.
 */
export interface GetAttestationOutputArgs {
    attestationVariant: pulumi.Input<string>;
    csp: pulumi.Input<string>;
    image: pulumi.Input<inputs.GetAttestationImageArgs>;
    insecure?: pulumi.Input<boolean>;
    maaUrl?: pulumi.Input<string>;
}
