// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { FolderIAMMemberArgs } from "./folderIAMMember";
export type FolderIAMMember = import("./folderIAMMember").FolderIAMMember;
export const FolderIAMMember: typeof import("./folderIAMMember").FolderIAMMember = null as any;
utilities.lazyLoad(exports, ["FolderIAMMember"], () => require("./folderIAMMember"));

export { FolderIAMMemberListArgs } from "./folderIAMMemberList";
export type FolderIAMMemberList = import("./folderIAMMemberList").FolderIAMMemberList;
export const FolderIAMMemberList: typeof import("./folderIAMMemberList").FolderIAMMemberList = null as any;
utilities.lazyLoad(exports, ["FolderIAMMemberList"], () => require("./folderIAMMemberList"));

export { FolderIAMMemberPatchArgs } from "./folderIAMMemberPatch";
export type FolderIAMMemberPatch = import("./folderIAMMemberPatch").FolderIAMMemberPatch;
export const FolderIAMMemberPatch: typeof import("./folderIAMMemberPatch").FolderIAMMemberPatch = null as any;
utilities.lazyLoad(exports, ["FolderIAMMemberPatch"], () => require("./folderIAMMemberPatch"));

export { OrganizationIAMMemberArgs } from "./organizationIAMMember";
export type OrganizationIAMMember = import("./organizationIAMMember").OrganizationIAMMember;
export const OrganizationIAMMember: typeof import("./organizationIAMMember").OrganizationIAMMember = null as any;
utilities.lazyLoad(exports, ["OrganizationIAMMember"], () => require("./organizationIAMMember"));

export { OrganizationIAMMemberListArgs } from "./organizationIAMMemberList";
export type OrganizationIAMMemberList = import("./organizationIAMMemberList").OrganizationIAMMemberList;
export const OrganizationIAMMemberList: typeof import("./organizationIAMMemberList").OrganizationIAMMemberList = null as any;
utilities.lazyLoad(exports, ["OrganizationIAMMemberList"], () => require("./organizationIAMMemberList"));

export { OrganizationIAMMemberPatchArgs } from "./organizationIAMMemberPatch";
export type OrganizationIAMMemberPatch = import("./organizationIAMMemberPatch").OrganizationIAMMemberPatch;
export const OrganizationIAMMemberPatch: typeof import("./organizationIAMMemberPatch").OrganizationIAMMemberPatch = null as any;
utilities.lazyLoad(exports, ["OrganizationIAMMemberPatch"], () => require("./organizationIAMMemberPatch"));

export { ProjectIAMMemberArgs } from "./projectIAMMember";
export type ProjectIAMMember = import("./projectIAMMember").ProjectIAMMember;
export const ProjectIAMMember: typeof import("./projectIAMMember").ProjectIAMMember = null as any;
utilities.lazyLoad(exports, ["ProjectIAMMember"], () => require("./projectIAMMember"));

export { ProjectIAMMemberListArgs } from "./projectIAMMemberList";
export type ProjectIAMMemberList = import("./projectIAMMemberList").ProjectIAMMemberList;
export const ProjectIAMMemberList: typeof import("./projectIAMMemberList").ProjectIAMMemberList = null as any;
utilities.lazyLoad(exports, ["ProjectIAMMemberList"], () => require("./projectIAMMemberList"));

export { ProjectIAMMemberPatchArgs } from "./projectIAMMemberPatch";
export type ProjectIAMMemberPatch = import("./projectIAMMemberPatch").ProjectIAMMemberPatch;
export const ProjectIAMMemberPatch: typeof import("./projectIAMMemberPatch").ProjectIAMMemberPatch = null as any;
utilities.lazyLoad(exports, ["ProjectIAMMemberPatch"], () => require("./projectIAMMemberPatch"));

export { ServiceAccountIAMMemberArgs } from "./serviceAccountIAMMember";
export type ServiceAccountIAMMember = import("./serviceAccountIAMMember").ServiceAccountIAMMember;
export const ServiceAccountIAMMember: typeof import("./serviceAccountIAMMember").ServiceAccountIAMMember = null as any;
utilities.lazyLoad(exports, ["ServiceAccountIAMMember"], () => require("./serviceAccountIAMMember"));

export { ServiceAccountIAMMemberListArgs } from "./serviceAccountIAMMemberList";
export type ServiceAccountIAMMemberList = import("./serviceAccountIAMMemberList").ServiceAccountIAMMemberList;
export const ServiceAccountIAMMemberList: typeof import("./serviceAccountIAMMemberList").ServiceAccountIAMMemberList = null as any;
utilities.lazyLoad(exports, ["ServiceAccountIAMMemberList"], () => require("./serviceAccountIAMMemberList"));

export { ServiceAccountIAMMemberPatchArgs } from "./serviceAccountIAMMemberPatch";
export type ServiceAccountIAMMemberPatch = import("./serviceAccountIAMMemberPatch").ServiceAccountIAMMemberPatch;
export const ServiceAccountIAMMemberPatch: typeof import("./serviceAccountIAMMemberPatch").ServiceAccountIAMMemberPatch = null as any;
utilities.lazyLoad(exports, ["ServiceAccountIAMMemberPatch"], () => require("./serviceAccountIAMMemberPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:FolderIAMMember":
                return new FolderIAMMember(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:FolderIAMMemberList":
                return new FolderIAMMemberList(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:FolderIAMMemberPatch":
                return new FolderIAMMemberPatch(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:OrganizationIAMMember":
                return new OrganizationIAMMember(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:OrganizationIAMMemberList":
                return new OrganizationIAMMemberList(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:OrganizationIAMMemberPatch":
                return new OrganizationIAMMemberPatch(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ProjectIAMMember":
                return new ProjectIAMMember(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ProjectIAMMemberList":
                return new ProjectIAMMemberList(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ProjectIAMMemberPatch":
                return new ProjectIAMMemberPatch(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ServiceAccountIAMMember":
                return new ServiceAccountIAMMember(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ServiceAccountIAMMemberList":
                return new ServiceAccountIAMMemberList(name, <any>undefined, { urn })
            case "kubernetes:cloudplatform.gcp.upbound.io/v1beta2:ServiceAccountIAMMemberPatch":
                return new ServiceAccountIAMMemberPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "cloudplatform.gcp.upbound.io/v1beta2", _module)
