// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema ExternalDns
 */
export class ExternalDns extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ExternalDns"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'nebula.io/v1alpha1',
    kind: 'ExternalDns',
  }

  /**
   * Renders a Kubernetes manifest for "ExternalDns".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ExternalDnsProps): any {
    return {
      ...ExternalDns.GVK,
      ...toJson_ExternalDnsProps(props),
    };
  }

  /**
   * Defines a "ExternalDns" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ExternalDnsProps) {
    super(scope, id, {
      ...ExternalDns.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...ExternalDns.GVK,
      ...toJson_ExternalDnsProps(resolved),
    };
  }
}

/**
 * @schema ExternalDns
 */
export interface ExternalDnsProps {
  /**
   * @schema ExternalDns#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema ExternalDns#spec
   */
  readonly spec: ExternalDnsSpec;
}

/**
 * Converts an object of type 'ExternalDnsProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ExternalDnsProps(obj: ExternalDnsProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ExternalDnsSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ExternalDnsSpec
 */
export interface ExternalDnsSpec {
  /**
   * Reference to a specific composition version
   *
   * @schema ExternalDnsSpec#compositionRef
   */
  readonly compositionRef?: ExternalDnsSpecCompositionRef;

  /**
   * Domains to manage DNS for
   *
   * @schema ExternalDnsSpec#domainFilters
   */
  readonly domainFilters?: string[];

  /**
   * Namespace to deploy external-dns
   *
   * @schema ExternalDnsSpec#namespace
   */
  readonly namespace?: string;

  /**
   * DNS record management policy
   *
   * @schema ExternalDnsSpec#policy
   */
  readonly policy?: ExternalDnsSpecPolicy;

  /**
   * GCP project ID
   *
   * @schema ExternalDnsSpec#project
   */
  readonly project: string;

  /**
   * Helm ProviderConfig reference for target cluster
   *
   * @schema ExternalDnsSpec#providerConfigRef
   */
  readonly providerConfigRef?: string;

  /**
   * Helm repository URL
   *
   * @schema ExternalDnsSpec#repository
   */
  readonly repository?: string;

  /**
   * Kubernetes resources to watch
   *
   * @schema ExternalDnsSpec#sources
   */
  readonly sources?: string[];

  /**
   * TXT record owner ID
   *
   * @schema ExternalDnsSpec#txtOwnerId
   */
  readonly txtOwnerId?: string;

  /**
   * TXT record prefix
   *
   * @schema ExternalDnsSpec#txtPrefix
   */
  readonly txtPrefix?: string;

  /**
   * Additional Helm values to merge
   *
   * @schema ExternalDnsSpec#values
   */
  readonly values?: any;

  /**
   * Helm chart version
   *
   * @schema ExternalDnsSpec#version
   */
  readonly version?: string;

  /**
   * Write connection secret to this reference
   *
   * @schema ExternalDnsSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: ExternalDnsSpecWriteConnectionSecretToRef;
}

/**
 * Converts an object of type 'ExternalDnsSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ExternalDnsSpec(obj: ExternalDnsSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'compositionRef': toJson_ExternalDnsSpecCompositionRef(obj.compositionRef),
    'domainFilters': obj.domainFilters?.map(y => y),
    'namespace': obj.namespace,
    'policy': obj.policy,
    'project': obj.project,
    'providerConfigRef': obj.providerConfigRef,
    'repository': obj.repository,
    'sources': obj.sources?.map(y => y),
    'txtOwnerId': obj.txtOwnerId,
    'txtPrefix': obj.txtPrefix,
    'values': obj.values,
    'version': obj.version,
    'writeConnectionSecretToRef': toJson_ExternalDnsSpecWriteConnectionSecretToRef(obj.writeConnectionSecretToRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a specific composition version
 *
 * @schema ExternalDnsSpecCompositionRef
 */
export interface ExternalDnsSpecCompositionRef {
  /**
   * Composition name (e.g., external-dns-v1, external-dns-v2)
   *
   * @schema ExternalDnsSpecCompositionRef#name
   */
  readonly name?: string;
}

/**
 * Converts an object of type 'ExternalDnsSpecCompositionRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ExternalDnsSpecCompositionRef(obj: ExternalDnsSpecCompositionRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * DNS record management policy
 *
 * @schema ExternalDnsSpecPolicy
 */
export enum ExternalDnsSpecPolicy {
  /** sync */
  SYNC = "sync",
  /** upsert-only */
  UPSERT_HYPHEN_ONLY = "upsert-only",
}

/**
 * Write connection secret to this reference
 *
 * @schema ExternalDnsSpecWriteConnectionSecretToRef
 */
export interface ExternalDnsSpecWriteConnectionSecretToRef {
  /**
   * Secret name
   *
   * @schema ExternalDnsSpecWriteConnectionSecretToRef#name
   */
  readonly name?: string;

  /**
   * Secret namespace
   *
   * @schema ExternalDnsSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'ExternalDnsSpecWriteConnectionSecretToRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ExternalDnsSpecWriteConnectionSecretToRef(obj: ExternalDnsSpecWriteConnectionSecretToRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

