// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema IngressNginx
 */
export class IngressNginx extends ApiObject {
  /**
   * Returns the apiVersion and kind for "IngressNginx"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'nebula.io/v1alpha1',
    kind: 'IngressNginx',
  }

  /**
   * Renders a Kubernetes manifest for "IngressNginx".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: IngressNginxProps): any {
    return {
      ...IngressNginx.GVK,
      ...toJson_IngressNginxProps(props),
    };
  }

  /**
   * Defines a "IngressNginx" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: IngressNginxProps) {
    super(scope, id, {
      ...IngressNginx.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...IngressNginx.GVK,
      ...toJson_IngressNginxProps(resolved),
    };
  }
}

/**
 * @schema IngressNginx
 */
export interface IngressNginxProps {
  /**
   * @schema IngressNginx#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema IngressNginx#spec
   */
  readonly spec: IngressNginxSpec;
}

/**
 * Converts an object of type 'IngressNginxProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxProps(obj: IngressNginxProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_IngressNginxSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema IngressNginxSpec
 */
export interface IngressNginxSpec {
  /**
   * Reference to a specific composition version
   *
   * @schema IngressNginxSpec#compositionRef
   */
  readonly compositionRef?: IngressNginxSpecCompositionRef;

  /**
   * Controller configuration
   *
   * @schema IngressNginxSpec#controller
   */
  readonly controller?: IngressNginxSpecController;

  /**
   * Create a static IP for the LoadBalancer
   *
   * @schema IngressNginxSpec#createStaticIp
   */
  readonly createStaticIp?: boolean;

  /**
   * Namespace to deploy ingress-nginx
   *
   * @schema IngressNginxSpec#namespace
   */
  readonly namespace?: string;

  /**
   * GCP project ID
   *
   * @schema IngressNginxSpec#project
   */
  readonly project: string;

  /**
   * Helm ProviderConfig reference for target cluster
   *
   * @schema IngressNginxSpec#providerConfigRef
   */
  readonly providerConfigRef?: string;

  /**
   * GCP region for static IP
   *
   * @schema IngressNginxSpec#region
   */
  readonly region: string;

  /**
   * Helm repository URL
   *
   * @schema IngressNginxSpec#repository
   */
  readonly repository?: string;

  /**
   * Name for the static IP resource
   *
   * @schema IngressNginxSpec#staticIpName
   */
  readonly staticIpName?: string;

  /**
   * Additional Helm values to merge
   *
   * @schema IngressNginxSpec#values
   */
  readonly values?: any;

  /**
   * Helm chart version
   *
   * @schema IngressNginxSpec#version
   */
  readonly version?: string;

  /**
   * Write connection secret to this reference
   *
   * @schema IngressNginxSpec#writeConnectionSecretToRef
   */
  readonly writeConnectionSecretToRef?: IngressNginxSpecWriteConnectionSecretToRef;
}

/**
 * Converts an object of type 'IngressNginxSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxSpec(obj: IngressNginxSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'compositionRef': toJson_IngressNginxSpecCompositionRef(obj.compositionRef),
    'controller': toJson_IngressNginxSpecController(obj.controller),
    'createStaticIp': obj.createStaticIp,
    'namespace': obj.namespace,
    'project': obj.project,
    'providerConfigRef': obj.providerConfigRef,
    'region': obj.region,
    'repository': obj.repository,
    'staticIpName': obj.staticIpName,
    'values': obj.values,
    'version': obj.version,
    'writeConnectionSecretToRef': toJson_IngressNginxSpecWriteConnectionSecretToRef(obj.writeConnectionSecretToRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Reference to a specific composition version
 *
 * @schema IngressNginxSpecCompositionRef
 */
export interface IngressNginxSpecCompositionRef {
  /**
   * Composition name (e.g., ingress-nginx-v1, ingress-nginx-v2)
   *
   * @schema IngressNginxSpecCompositionRef#name
   */
  readonly name?: string;
}

/**
 * Converts an object of type 'IngressNginxSpecCompositionRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxSpecCompositionRef(obj: IngressNginxSpecCompositionRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Controller configuration
 *
 * @schema IngressNginxSpecController
 */
export interface IngressNginxSpecController {
  /**
   * Number of controller replicas
   *
   * @schema IngressNginxSpecController#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema IngressNginxSpecController#service
   */
  readonly service?: IngressNginxSpecControllerService;
}

/**
 * Converts an object of type 'IngressNginxSpecController' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxSpecController(obj: IngressNginxSpecController | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'replicaCount': obj.replicaCount,
    'service': toJson_IngressNginxSpecControllerService(obj.service),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Write connection secret to this reference
 *
 * @schema IngressNginxSpecWriteConnectionSecretToRef
 */
export interface IngressNginxSpecWriteConnectionSecretToRef {
  /**
   * Secret name
   *
   * @schema IngressNginxSpecWriteConnectionSecretToRef#name
   */
  readonly name?: string;

  /**
   * Secret namespace
   *
   * @schema IngressNginxSpecWriteConnectionSecretToRef#namespace
   */
  readonly namespace?: string;
}

/**
 * Converts an object of type 'IngressNginxSpecWriteConnectionSecretToRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxSpecWriteConnectionSecretToRef(obj: IngressNginxSpecWriteConnectionSecretToRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema IngressNginxSpecControllerService
 */
export interface IngressNginxSpecControllerService {
  /**
   * @schema IngressNginxSpecControllerService#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: IngressNginxSpecControllerServiceExternalTrafficPolicy;

  /**
   * @schema IngressNginxSpecControllerService#type
   */
  readonly type?: IngressNginxSpecControllerServiceType;
}

/**
 * Converts an object of type 'IngressNginxSpecControllerService' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_IngressNginxSpecControllerService(obj: IngressNginxSpecControllerService | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'externalTrafficPolicy': obj.externalTrafficPolicy,
    'type': obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema IngressNginxSpecControllerServiceExternalTrafficPolicy
 */
export enum IngressNginxSpecControllerServiceExternalTrafficPolicy {
  /** Local */
  LOCAL = "Local",
  /** Cluster */
  CLUSTER = "Cluster",
}

/**
 * @schema IngressNginxSpecControllerServiceType
 */
export enum IngressNginxSpecControllerServiceType {
  /** LoadBalancer */
  LOAD_BALANCER = "LoadBalancer",
  /** NodePort */
  NODE_PORT = "NodePort",
  /** ClusterIP */
  CLUSTER_IP = "ClusterIP",
}

