// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * A CompositeResourceDefinition defines the schema for a new custom Kubernetes
API.

Read the Crossplane documentation for
[more information about CustomResourceDefinitions](https://docs.crossplane.io/latest/concepts/composite-resource-definitions).
 *
 * @schema CompositeResourceDefinition
 */
export class CompositeResourceDefinition extends ApiObject {
  /**
   * Returns the apiVersion and kind for "CompositeResourceDefinition"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'apiextensions.crossplane.io/v1',
    kind: 'CompositeResourceDefinition',
  }

  /**
   * Renders a Kubernetes manifest for "CompositeResourceDefinition".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: CompositeResourceDefinitionProps = {}): any {
    return {
      ...CompositeResourceDefinition.GVK,
      ...toJson_CompositeResourceDefinitionProps(props),
    };
  }

  /**
   * Defines a "CompositeResourceDefinition" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: CompositeResourceDefinitionProps = {}) {
    super(scope, id, {
      ...CompositeResourceDefinition.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...CompositeResourceDefinition.GVK,
      ...toJson_CompositeResourceDefinitionProps(resolved),
    };
  }
}

/**
 * A CompositeResourceDefinition defines the schema for a new custom Kubernetes
 * API.
 *
 * Read the Crossplane documentation for
 * [more information about CustomResourceDefinitions](https://docs.crossplane.io/latest/concepts/composite-resource-definitions).
 *
 * @schema CompositeResourceDefinition
 */
export interface CompositeResourceDefinitionProps {
  /**
   * @schema CompositeResourceDefinition#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * CompositeResourceDefinitionSpec specifies the desired state of the definition.
   *
   * @schema CompositeResourceDefinition#spec
   */
  readonly spec?: CompositeResourceDefinitionSpec;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionProps(obj: CompositeResourceDefinitionProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_CompositeResourceDefinitionSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * CompositeResourceDefinitionSpec specifies the desired state of the definition.
 *
 * @schema CompositeResourceDefinitionSpec
 */
export interface CompositeResourceDefinitionSpec {
  /**
   * ClaimNames specifies the names of an optional composite resource claim.
   * When claim names are specified Crossplane will create a namespaced
   * 'composite resource claim' CRD that corresponds to the defined composite
   * resource. This composite resource claim acts as a namespaced proxy for
   * the composite resource; creating, updating, or deleting the claim will
   * create, update, or delete a corresponding composite resource. You may add
   * claim names to an existing CompositeResourceDefinition, but they cannot
   * be changed or removed once they have been set.
   *
   * @schema CompositeResourceDefinitionSpec#claimNames
   */
  readonly claimNames?: CompositeResourceDefinitionSpecClaimNames;

  /**
   * ConnectionSecretKeys is the list of keys that will be exposed to the end
   * user of the defined kind.
   * If the list is empty, all keys will be published.
   *
   * @schema CompositeResourceDefinitionSpec#connectionSecretKeys
   */
  readonly connectionSecretKeys?: string[];

  /**
   * Conversion defines all conversion settings for the defined Composite resource.
   *
   * @schema CompositeResourceDefinitionSpec#conversion
   */
  readonly conversion?: CompositeResourceDefinitionSpecConversion;

  /**
   * DefaultCompositeDeletePolicy is the policy used when deleting the Composite
   * that is associated with the Claim if no policy has been specified.
   *
   * @schema CompositeResourceDefinitionSpec#defaultCompositeDeletePolicy
   */
  readonly defaultCompositeDeletePolicy?: CompositeResourceDefinitionSpecDefaultCompositeDeletePolicy;

  /**
   * DefaultCompositionRef refers to the Composition resource that will be used
   * in case no composition selector is given.
   *
   * @schema CompositeResourceDefinitionSpec#defaultCompositionRef
   */
  readonly defaultCompositionRef?: CompositeResourceDefinitionSpecDefaultCompositionRef;

  /**
   * DefaultCompositionUpdatePolicy is the policy used when updating composites after a new
   * Composition Revision has been created if no policy has been specified on the composite.
   *
   * @schema CompositeResourceDefinitionSpec#defaultCompositionUpdatePolicy
   */
  readonly defaultCompositionUpdatePolicy?: CompositeResourceDefinitionSpecDefaultCompositionUpdatePolicy;

  /**
   * EnforcedCompositionRef refers to the Composition resource that will be used
   * by all composite instances whose schema is defined by this definition.
   *
   * @schema CompositeResourceDefinitionSpec#enforcedCompositionRef
   */
  readonly enforcedCompositionRef?: CompositeResourceDefinitionSpecEnforcedCompositionRef;

  /**
   * Group specifies the API group of the defined composite resource.
   * Composite resources are served under `/apis/<group>/...`. Must match the
   * name of the XRD (in the form `<names.plural>.<group>`).
   *
   * @schema CompositeResourceDefinitionSpec#group
   */
  readonly group: string;

  /**
   * Metadata specifies the desired metadata for the defined composite resource and claim CRD's.
   *
   * @schema CompositeResourceDefinitionSpec#metadata
   */
  readonly metadata?: CompositeResourceDefinitionSpecMetadata;

  /**
   * Names specifies the resource and kind names of the defined composite
   * resource.
   *
   * @schema CompositeResourceDefinitionSpec#names
   */
  readonly names: CompositeResourceDefinitionSpecNames;

  /**
   * Versions is the list of all API versions of the defined composite
   * resource. Version names are used to compute the order in which served
   * versions are listed in API discovery. If the version string is
   * "kube-like", it will sort above non "kube-like" version strings, which
   * are ordered lexicographically. "Kube-like" versions start with a "v",
   * then are followed by a number (the major version), then optionally the
   * string "alpha" or "beta" and another number (the minor version). These
   * are sorted first by GA > beta > alpha (where GA is a version with no
   * suffix such as beta or alpha), and then by comparing major version, then
   * minor version. An example sorted list of versions: v10, v2, v1, v11beta2,
   * v10beta3, v3beta1, v12alpha1, v11alpha2, foo1, foo10.
   *
   * @schema CompositeResourceDefinitionSpec#versions
   */
  readonly versions: CompositeResourceDefinitionSpecVersions[];
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpec(obj: CompositeResourceDefinitionSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'claimNames': toJson_CompositeResourceDefinitionSpecClaimNames(obj.claimNames),
    'connectionSecretKeys': obj.connectionSecretKeys?.map(y => y),
    'conversion': toJson_CompositeResourceDefinitionSpecConversion(obj.conversion),
    'defaultCompositeDeletePolicy': obj.defaultCompositeDeletePolicy,
    'defaultCompositionRef': toJson_CompositeResourceDefinitionSpecDefaultCompositionRef(obj.defaultCompositionRef),
    'defaultCompositionUpdatePolicy': obj.defaultCompositionUpdatePolicy,
    'enforcedCompositionRef': toJson_CompositeResourceDefinitionSpecEnforcedCompositionRef(obj.enforcedCompositionRef),
    'group': obj.group,
    'metadata': toJson_CompositeResourceDefinitionSpecMetadata(obj.metadata),
    'names': toJson_CompositeResourceDefinitionSpecNames(obj.names),
    'versions': obj.versions?.map(y => toJson_CompositeResourceDefinitionSpecVersions(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ClaimNames specifies the names of an optional composite resource claim.
 * When claim names are specified Crossplane will create a namespaced
 * 'composite resource claim' CRD that corresponds to the defined composite
 * resource. This composite resource claim acts as a namespaced proxy for
 * the composite resource; creating, updating, or deleting the claim will
 * create, update, or delete a corresponding composite resource. You may add
 * claim names to an existing CompositeResourceDefinition, but they cannot
 * be changed or removed once they have been set.
 *
 * @schema CompositeResourceDefinitionSpecClaimNames
 */
export interface CompositeResourceDefinitionSpecClaimNames {
  /**
   * categories is a list of grouped resources this custom resource belongs to (e.g. 'all').
   * This is published in API discovery documents, and used by clients to support invocations like
   * `kubectl get all`.
   *
   * @schema CompositeResourceDefinitionSpecClaimNames#categories
   */
  readonly categories?: string[];

  /**
   * kind is the serialized kind of the resource. It is normally CamelCase and singular.
   * Custom resource instances will use this value as the `kind` attribute in API calls.
   *
   * @schema CompositeResourceDefinitionSpecClaimNames#kind
   */
  readonly kind: string;

  /**
   * listKind is the serialized kind of the list for this resource. Defaults to "`kind`List".
   *
   * @default kind`List".
   * @schema CompositeResourceDefinitionSpecClaimNames#listKind
   */
  readonly listKind?: string;

  /**
   * plural is the plural name of the resource to serve.
   * The custom resources are served under `/apis/<group>/<version>/.../<plural>`.
   * Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`).
   * Must be all lowercase.
   *
   * @schema CompositeResourceDefinitionSpecClaimNames#plural
   */
  readonly plural: string;

  /**
   * shortNames are short names for the resource, exposed in API discovery documents,
   * and used by clients to support invocations like `kubectl get <shortname>`.
   * It must be all lowercase.
   *
   * @schema CompositeResourceDefinitionSpecClaimNames#shortNames
   */
  readonly shortNames?: string[];

  /**
   * singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`.
   *
   * @default lowercased `kind`.
   * @schema CompositeResourceDefinitionSpecClaimNames#singular
   */
  readonly singular?: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecClaimNames' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecClaimNames(obj: CompositeResourceDefinitionSpecClaimNames | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'categories': obj.categories?.map(y => y),
    'kind': obj.kind,
    'listKind': obj.listKind,
    'plural': obj.plural,
    'shortNames': obj.shortNames?.map(y => y),
    'singular': obj.singular,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Conversion defines all conversion settings for the defined Composite resource.
 *
 * @schema CompositeResourceDefinitionSpecConversion
 */
export interface CompositeResourceDefinitionSpecConversion {
  /**
   * strategy specifies how custom resources are converted between versions. Allowed values are:
   * - `"None"`: The converter only change the apiVersion and would not touch any other field in the custom resource.
   * - `"Webhook"`: API Server will call to an external webhook to do the conversion. Additional information
   * is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.
   *
   * @schema CompositeResourceDefinitionSpecConversion#strategy
   */
  readonly strategy: string;

  /**
   * webhook describes how to call the conversion webhook. Required when `strategy` is set to `"Webhook"`.
   *
   * @schema CompositeResourceDefinitionSpecConversion#webhook
   */
  readonly webhook?: CompositeResourceDefinitionSpecConversionWebhook;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecConversion' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecConversion(obj: CompositeResourceDefinitionSpecConversion | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'strategy': obj.strategy,
    'webhook': toJson_CompositeResourceDefinitionSpecConversionWebhook(obj.webhook),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * DefaultCompositeDeletePolicy is the policy used when deleting the Composite
 * that is associated with the Claim if no policy has been specified.
 *
 * @schema CompositeResourceDefinitionSpecDefaultCompositeDeletePolicy
 */
export enum CompositeResourceDefinitionSpecDefaultCompositeDeletePolicy {
  /** Background */
  BACKGROUND = "Background",
  /** Foreground */
  FOREGROUND = "Foreground",
}

/**
 * DefaultCompositionRef refers to the Composition resource that will be used
 * in case no composition selector is given.
 *
 * @schema CompositeResourceDefinitionSpecDefaultCompositionRef
 */
export interface CompositeResourceDefinitionSpecDefaultCompositionRef {
  /**
   * Name of the Composition.
   *
   * @schema CompositeResourceDefinitionSpecDefaultCompositionRef#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecDefaultCompositionRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecDefaultCompositionRef(obj: CompositeResourceDefinitionSpecDefaultCompositionRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * DefaultCompositionUpdatePolicy is the policy used when updating composites after a new
 * Composition Revision has been created if no policy has been specified on the composite.
 *
 * @schema CompositeResourceDefinitionSpecDefaultCompositionUpdatePolicy
 */
export enum CompositeResourceDefinitionSpecDefaultCompositionUpdatePolicy {
  /** Automatic */
  AUTOMATIC = "Automatic",
  /** Manual */
  MANUAL = "Manual",
}

/**
 * EnforcedCompositionRef refers to the Composition resource that will be used
 * by all composite instances whose schema is defined by this definition.
 *
 * @schema CompositeResourceDefinitionSpecEnforcedCompositionRef
 */
export interface CompositeResourceDefinitionSpecEnforcedCompositionRef {
  /**
   * Name of the Composition.
   *
   * @schema CompositeResourceDefinitionSpecEnforcedCompositionRef#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecEnforcedCompositionRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecEnforcedCompositionRef(obj: CompositeResourceDefinitionSpecEnforcedCompositionRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Metadata specifies the desired metadata for the defined composite resource and claim CRD's.
 *
 * @schema CompositeResourceDefinitionSpecMetadata
 */
export interface CompositeResourceDefinitionSpecMetadata {
  /**
   * Annotations is an unstructured key value map stored with a resource that may be
   * set by external tools to store and retrieve arbitrary metadata. They are not
   * queryable and should be preserved when modifying objects.
   * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
   *
   * @schema CompositeResourceDefinitionSpecMetadata#annotations
   */
  readonly annotations?: { [key: string]: string };

  /**
   * Map of string keys and values that can be used to organize and categorize
   * (scope and select) objects. May match selectors of replication controllers
   * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
   * and services.
   * These labels are added to the composite resource and claim CRD's in addition
   * to any labels defined by `CompositionResourceDefinition` `metadata.labels`.
   *
   * @schema CompositeResourceDefinitionSpecMetadata#labels
   */
  readonly labels?: { [key: string]: string };
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecMetadata' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecMetadata(obj: CompositeResourceDefinitionSpecMetadata | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'annotations': ((obj.annotations) === undefined) ? undefined : (Object.entries(obj.annotations).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'labels': ((obj.labels) === undefined) ? undefined : (Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Names specifies the resource and kind names of the defined composite
 * resource.
 *
 * @schema CompositeResourceDefinitionSpecNames
 */
export interface CompositeResourceDefinitionSpecNames {
  /**
   * categories is a list of grouped resources this custom resource belongs to (e.g. 'all').
   * This is published in API discovery documents, and used by clients to support invocations like
   * `kubectl get all`.
   *
   * @schema CompositeResourceDefinitionSpecNames#categories
   */
  readonly categories?: string[];

  /**
   * kind is the serialized kind of the resource. It is normally CamelCase and singular.
   * Custom resource instances will use this value as the `kind` attribute in API calls.
   *
   * @schema CompositeResourceDefinitionSpecNames#kind
   */
  readonly kind: string;

  /**
   * listKind is the serialized kind of the list for this resource. Defaults to "`kind`List".
   *
   * @default kind`List".
   * @schema CompositeResourceDefinitionSpecNames#listKind
   */
  readonly listKind?: string;

  /**
   * plural is the plural name of the resource to serve.
   * The custom resources are served under `/apis/<group>/<version>/.../<plural>`.
   * Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`).
   * Must be all lowercase.
   *
   * @schema CompositeResourceDefinitionSpecNames#plural
   */
  readonly plural: string;

  /**
   * shortNames are short names for the resource, exposed in API discovery documents,
   * and used by clients to support invocations like `kubectl get <shortname>`.
   * It must be all lowercase.
   *
   * @schema CompositeResourceDefinitionSpecNames#shortNames
   */
  readonly shortNames?: string[];

  /**
   * singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`.
   *
   * @default lowercased `kind`.
   * @schema CompositeResourceDefinitionSpecNames#singular
   */
  readonly singular?: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecNames' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecNames(obj: CompositeResourceDefinitionSpecNames | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'categories': obj.categories?.map(y => y),
    'kind': obj.kind,
    'listKind': obj.listKind,
    'plural': obj.plural,
    'shortNames': obj.shortNames?.map(y => y),
    'singular': obj.singular,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * CompositeResourceDefinitionVersion describes a version of an XR.
 *
 * @schema CompositeResourceDefinitionSpecVersions
 */
export interface CompositeResourceDefinitionSpecVersions {
  /**
   * AdditionalPrinterColumns specifies additional columns returned in Table
   * output. If no columns are specified, a single column displaying the age
   * of the custom resource is used. See the following link for details:
   * https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables
   *
   * @schema CompositeResourceDefinitionSpecVersions#additionalPrinterColumns
   */
  readonly additionalPrinterColumns?: CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns[];

  /**
   * The deprecated field specifies that this version is deprecated and should
   * not be used.
   *
   * @schema CompositeResourceDefinitionSpecVersions#deprecated
   */
  readonly deprecated?: boolean;

  /**
   * DeprecationWarning specifies the message that should be shown to the user
   * when using this version.
   *
   * @schema CompositeResourceDefinitionSpecVersions#deprecationWarning
   */
  readonly deprecationWarning?: string;

  /**
   * Name of this version, e.g. “v1”, “v2beta1”, etc. Composite resources are
   * served under this version at `/apis/<group>/<version>/...` if `served` is
   * true.
   *
   * @schema CompositeResourceDefinitionSpecVersions#name
   */
  readonly name: string;

  /**
   * Referenceable specifies that this version may be referenced by a
   * Composition in order to configure which resources an XR may be composed
   * of. Exactly one version must be marked as referenceable; all Compositions
   * must target only the referenceable version. The referenceable version
   * must be served. It's mapped to the CRD's `spec.versions[*].storage` field.
   *
   * @schema CompositeResourceDefinitionSpecVersions#referenceable
   */
  readonly referenceable: boolean;

  /**
   * Schema describes the schema used for validation, pruning, and defaulting
   * of this version of the defined composite resource. Fields required by all
   * composite resources will be injected into this schema automatically, and
   * will override equivalently named fields in this schema. Omitting this
   * schema results in a schema that contains only the fields required by all
   * composite resources.
   *
   * @schema CompositeResourceDefinitionSpecVersions#schema
   */
  readonly schema?: CompositeResourceDefinitionSpecVersionsSchema;

  /**
   * Served specifies that this version should be served via REST APIs.
   *
   * @schema CompositeResourceDefinitionSpecVersions#served
   */
  readonly served: boolean;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecVersions' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecVersions(obj: CompositeResourceDefinitionSpecVersions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'additionalPrinterColumns': obj.additionalPrinterColumns?.map(y => toJson_CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns(y)),
    'deprecated': obj.deprecated,
    'deprecationWarning': obj.deprecationWarning,
    'name': obj.name,
    'referenceable': obj.referenceable,
    'schema': toJson_CompositeResourceDefinitionSpecVersionsSchema(obj.schema),
    'served': obj.served,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * webhook describes how to call the conversion webhook. Required when `strategy` is set to `"Webhook"`.
 *
 * @schema CompositeResourceDefinitionSpecConversionWebhook
 */
export interface CompositeResourceDefinitionSpecConversionWebhook {
  /**
   * clientConfig is the instructions for how to call the webhook if strategy is `Webhook`.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhook#clientConfig
   */
  readonly clientConfig?: CompositeResourceDefinitionSpecConversionWebhookClientConfig;

  /**
   * conversionReviewVersions is an ordered list of preferred `ConversionReview`
   * versions the Webhook expects. The API server will use the first version in
   * the list which it supports. If none of the versions specified in this list
   * are supported by API server, conversion will fail for the custom resource.
   * If a persisted Webhook configuration specifies allowed versions and does not
   * include any versions known to the API Server, calls to the webhook will fail.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhook#conversionReviewVersions
   */
  readonly conversionReviewVersions: string[];
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecConversionWebhook' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecConversionWebhook(obj: CompositeResourceDefinitionSpecConversionWebhook | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clientConfig': toJson_CompositeResourceDefinitionSpecConversionWebhookClientConfig(obj.clientConfig),
    'conversionReviewVersions': obj.conversionReviewVersions?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * CustomResourceColumnDefinition specifies a column for server side printing.
 *
 * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns
 */
export interface CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns {
  /**
   * description is a human readable description of this column.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#description
   */
  readonly description?: string;

  /**
   * format is an optional OpenAPI type definition for this column. The 'name' format is applied
   * to the primary identifier column to assist in clients identifying column is the resource name.
   * See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#format
   */
  readonly format?: string;

  /**
   * jsonPath is a simple JSON path (i.e. with array notation) which is evaluated against
   * each custom resource to produce the value for this column.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#jsonPath
   */
  readonly jsonPath: string;

  /**
   * name is a human readable name for the column.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#name
   */
  readonly name: string;

  /**
   * priority is an integer defining the relative importance of this column compared to others. Lower
   * numbers are considered higher priority. Columns that may be omitted in limited space scenarios
   * should be given a priority greater than 0.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#priority
   */
  readonly priority?: number;

  /**
   * type is an OpenAPI type definition for this column.
   * See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.
   *
   * @schema CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns#type
   */
  readonly type: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns(obj: CompositeResourceDefinitionSpecVersionsAdditionalPrinterColumns | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'description': obj.description,
    'format': obj.format,
    'jsonPath': obj.jsonPath,
    'name': obj.name,
    'priority': obj.priority,
    'type': obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Schema describes the schema used for validation, pruning, and defaulting
 * of this version of the defined composite resource. Fields required by all
 * composite resources will be injected into this schema automatically, and
 * will override equivalently named fields in this schema. Omitting this
 * schema results in a schema that contains only the fields required by all
 * composite resources.
 *
 * @schema CompositeResourceDefinitionSpecVersionsSchema
 */
export interface CompositeResourceDefinitionSpecVersionsSchema {
  /**
   * OpenAPIV3Schema is the OpenAPI v3 schema to use for validation and
   * pruning.
   *
   * @schema CompositeResourceDefinitionSpecVersionsSchema#openAPIV3Schema
   */
  readonly openApiv3Schema?: any;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecVersionsSchema' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecVersionsSchema(obj: CompositeResourceDefinitionSpecVersionsSchema | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'openAPIV3Schema': obj.openApiv3Schema,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * clientConfig is the instructions for how to call the webhook if strategy is `Webhook`.
 *
 * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfig
 */
export interface CompositeResourceDefinitionSpecConversionWebhookClientConfig {
  /**
   * caBundle is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.
   * If unspecified, system trust roots on the apiserver are used.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfig#caBundle
   */
  readonly caBundle?: string;

  /**
   * service is a reference to the service for this webhook. Either
   * service or url must be specified.
   *
   * If the webhook is running within the cluster, then you should use `service`.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfig#service
   */
  readonly service?: CompositeResourceDefinitionSpecConversionWebhookClientConfigService;

  /**
   * url gives the location of the webhook, in standard URL form
   * (`scheme://host:port/path`). Exactly one of `url` or `service`
   * must be specified.
   *
   * The `host` should not refer to a service running in the cluster; use
   * the `service` field instead. The host might be resolved via external
   * DNS in some apiservers (e.g., `kube-apiserver` cannot resolve
   * in-cluster DNS as that would be a layering violation). `host` may
   * also be an IP address.
   *
   * Please note that using `localhost` or `127.0.0.1` as a `host` is
   * risky unless you take great care to run this webhook on all hosts
   * which run an apiserver which might need to make calls to this
   * webhook. Such installs are likely to be non-portable, i.e., not easy
   * to turn up in a new cluster.
   *
   * The scheme must be "https"; the URL must begin with "https://".
   *
   * A path is optional, and if present may be any string permissible in
   * a URL. You may use the path to pass an arbitrary string to the
   * webhook, for example, a cluster identifier.
   *
   * Attempting to use a user or basic auth e.g. "user:password@" is not
   * allowed. Fragments ("#...") and query parameters ("?...") are not
   * allowed, either.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfig#url
   */
  readonly url?: string;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecConversionWebhookClientConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecConversionWebhookClientConfig(obj: CompositeResourceDefinitionSpecConversionWebhookClientConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'caBundle': obj.caBundle,
    'service': toJson_CompositeResourceDefinitionSpecConversionWebhookClientConfigService(obj.service),
    'url': obj.url,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * service is a reference to the service for this webhook. Either
 * service or url must be specified.
 *
 * If the webhook is running within the cluster, then you should use `service`.
 *
 * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfigService
 */
export interface CompositeResourceDefinitionSpecConversionWebhookClientConfigService {
  /**
   * name is the name of the service.
   * Required
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfigService#name
   */
  readonly name: string;

  /**
   * namespace is the namespace of the service.
   * Required
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfigService#namespace
   */
  readonly namespace: string;

  /**
   * path is an optional URL path at which the webhook will be contacted.
   *
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfigService#path
   */
  readonly path?: string;

  /**
   * port is an optional service port at which the webhook will be contacted.
   * `port` should be a valid port number (1-65535, inclusive).
   * Defaults to 443 for backward compatibility.
   *
   * @default 443 for backward compatibility.
   * @schema CompositeResourceDefinitionSpecConversionWebhookClientConfigService#port
   */
  readonly port?: number;
}

/**
 * Converts an object of type 'CompositeResourceDefinitionSpecConversionWebhookClientConfigService' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CompositeResourceDefinitionSpecConversionWebhookClientConfigService(obj: CompositeResourceDefinitionSpecConversionWebhookClientConfigService | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
    'path': obj.path,
    'port': obj.port,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

