apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certmanagers.nebula.io
spec:
  group: nebula.io
  names:
    kind: CertManager
    plural: certmanagers
    singular: certmanager
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              properties:
                acmeEmail:
                  description: Email address for ACME (Let's Encrypt) registration
                  type: string
                compositionRef:
                  description: Reference to a specific composition version
                  properties:
                    name:
                      description: Composition name (e.g., cert-manager-v1, cert-manager-v2)
                      type: string
                  type: object
                namespace:
                  default: cert-manager
                  description: Namespace to deploy cert-manager
                  type: string
                providerConfigRef:
                  default: default
                  description: Helm ProviderConfig reference for target cluster
                  type: string
                repository:
                  default: https://charts.jetstack.io
                  description: Helm repository URL
                  type: string
                values:
                  description: Additional Helm values to merge
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                version:
                  default: v1.15.2
                  description: Helm chart version
                  type: string
                writeConnectionSecretToRef:
                  type: object
                  description: Write connection secret to this reference
                  properties:
                    name:
                      type: string
                      description: Secret name
                    namespace:
                      type: string
                      description: Secret namespace
              required:
                - acmeEmail
              type: object
            status:
              properties:
                ready:
                  description: Whether cert-manager is ready
                  type: boolean
              type: object
