apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gcpinfrastructures.nebula.io
spec:
  group: nebula.io
  names:
    kind: GcpInfrastructure
    plural: gcpinfrastructures
    singular: gcpinfrastructure
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              properties:
                compositionRef:
                  description: Reference to a specific composition version
                  properties:
                    name:
                      description: Composition name (e.g., gcp-infrastructure-v1,
                        gcp-infrastructure-v2)
                      type: string
                  type: object
                gke:
                  description: GKE cluster configuration
                  properties:
                    deletionProtection:
                      default: true
                      description: Enable deletion protection
                      type: boolean
                    location:
                      description: Cluster location (zone or region)
                      type: string
                    name:
                      description: Cluster name
                      type: string
                    releaseChannel:
                      default: REGULAR
                      description: GKE release channel
                      enum:
                        - RAPID
                        - REGULAR
                        - STABLE
                      type: string
                  required:
                    - name
                    - location
                  type: object
                network:
                  description: VPC network configuration
                  properties:
                    cidr:
                      default: 10.10.0.0/16
                      description: Primary CIDR for the subnet
                      type: string
                    podsCidr:
                      default: 10.20.0.0/16
                      description: Secondary CIDR for pods
                      type: string
                    servicesCidr:
                      default: 10.30.0.0/16
                      description: Secondary CIDR for services
                      type: string
                  type: object
                nodePools:
                  description: Node pool configurations
                  items:
                    properties:
                      diskSizeGb:
                        default: 100
                        description: Disk size in GB
                        type: integer
                      imageType:
                        description: Node image type (e.g., UBUNTU_CONTAINERD)
                        type: string
                      labels:
                        additionalProperties:
                          type: string
                        description: Node labels
                        type: object
                      machineType:
                        default: e2-standard-4
                        description: GCP machine type
                        type: string
                      maxNodes:
                        default: 3
                        description: Maximum number of nodes
                        type: integer
                      minNodes:
                        default: 1
                        description: Minimum number of nodes
                        type: integer
                      name:
                        description: Node pool name
                        type: string
                      spot:
                        default: false
                        description: Use spot/preemptible VMs
                        type: boolean
                      taints:
                        description: Node taints
                        items:
                          properties:
                            effect:
                              enum:
                                - NoSchedule
                                - PreferNoSchedule
                                - NoExecute
                              type: string
                            key:
                              type: string
                            value:
                              type: string
                          required:
                            - key
                            - effect
                          type: object
                        type: array
                    required:
                      - name
                    type: object
                  type: array
                project:
                  description: GCP project ID
                  type: string
                region:
                  description: GCP region (e.g., europe-west3)
                  type: string
                writeConnectionSecretToRef:
                  type: object
                  description: Write connection secret to this reference
                  properties:
                    name:
                      type: string
                      description: Secret name
                    namespace:
                      type: string
                      description: Secret namespace
              required:
                - project
                - region
                - gke
                - nodePools
              type: object
            status:
              properties:
                clusterCaCertificate:
                  description: GKE cluster CA certificate
                  type: string
                clusterEndpoint:
                  description: GKE cluster endpoint
                  type: string
                networkSelfLink:
                  description: VPC network self link
                  type: string
              type: object
