// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export type { ProjectArgs } from "./project";
import { Project } from "./project";
export { Project };

export type { ProjectListArgs } from "./projectList";
import { ProjectList } from "./projectList";
export { ProjectList };

export type { ProjectPatchArgs } from "./projectPatch";
import { ProjectPatch } from "./projectPatch";
export { ProjectPatch };


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:projects.argocd.crossplane.io/v1alpha1:Project":
                return new Project(name, <any>undefined, { urn })
            case "kubernetes:projects.argocd.crossplane.io/v1alpha1:ProjectList":
                return new ProjectList(name, <any>undefined, { urn })
            case "kubernetes:projects.argocd.crossplane.io/v1alpha1:ProjectPatch":
                return new ProjectPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "projects.argocd.crossplane.io/v1alpha1", _module)
