// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export type { ProviderArgs } from "./provider";
import { Provider } from "./provider";
export { Provider };


// Export sub-modules:
import * as applications from "./applications";
import * as applicationsets from "./applicationsets";
import * as argocd from "./argocd";
import * as cluster from "./cluster";
import * as projects from "./projects";
import * as repositories from "./repositories";
import * as types from "./types";

export {
    applications,
    applicationsets,
    argocd,
    cluster,
    projects,
    repositories,
    types,
};
pulumi.runtime.registerResourcePackage("crds", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:kubernetes") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
