// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export type { ApplicationSetArgs } from "./applicationSet";
import { ApplicationSet } from "./applicationSet";
export { ApplicationSet };

export type { ApplicationSetListArgs } from "./applicationSetList";
import { ApplicationSetList } from "./applicationSetList";
export { ApplicationSetList };

export type { ApplicationSetPatchArgs } from "./applicationSetPatch";
import { ApplicationSetPatch } from "./applicationSetPatch";
export { ApplicationSetPatch };


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:applicationsets.argocd.crossplane.io/v1alpha1:ApplicationSet":
                return new ApplicationSet(name, <any>undefined, { urn })
            case "kubernetes:applicationsets.argocd.crossplane.io/v1alpha1:ApplicationSetList":
                return new ApplicationSetList(name, <any>undefined, { urn })
            case "kubernetes:applicationsets.argocd.crossplane.io/v1alpha1:ApplicationSetPatch":
                return new ApplicationSetPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "applicationsets.argocd.crossplane.io/v1alpha1", _module)
