// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { BucketArgs } from "./bucket";
export type Bucket = import("./bucket").Bucket;
export const Bucket: typeof import("./bucket").Bucket = null as any;
utilities.lazyLoad(exports, ["Bucket"], () => require("./bucket"));

export { BucketIAMMemberArgs } from "./bucketIAMMember";
export type BucketIAMMember = import("./bucketIAMMember").BucketIAMMember;
export const BucketIAMMember: typeof import("./bucketIAMMember").BucketIAMMember = null as any;
utilities.lazyLoad(exports, ["BucketIAMMember"], () => require("./bucketIAMMember"));

export { BucketIAMMemberListArgs } from "./bucketIAMMemberList";
export type BucketIAMMemberList = import("./bucketIAMMemberList").BucketIAMMemberList;
export const BucketIAMMemberList: typeof import("./bucketIAMMemberList").BucketIAMMemberList = null as any;
utilities.lazyLoad(exports, ["BucketIAMMemberList"], () => require("./bucketIAMMemberList"));

export { BucketIAMMemberPatchArgs } from "./bucketIAMMemberPatch";
export type BucketIAMMemberPatch = import("./bucketIAMMemberPatch").BucketIAMMemberPatch;
export const BucketIAMMemberPatch: typeof import("./bucketIAMMemberPatch").BucketIAMMemberPatch = null as any;
utilities.lazyLoad(exports, ["BucketIAMMemberPatch"], () => require("./bucketIAMMemberPatch"));

export { BucketListArgs } from "./bucketList";
export type BucketList = import("./bucketList").BucketList;
export const BucketList: typeof import("./bucketList").BucketList = null as any;
utilities.lazyLoad(exports, ["BucketList"], () => require("./bucketList"));

export { BucketObjectArgs } from "./bucketObject";
export type BucketObject = import("./bucketObject").BucketObject;
export const BucketObject: typeof import("./bucketObject").BucketObject = null as any;
utilities.lazyLoad(exports, ["BucketObject"], () => require("./bucketObject"));

export { BucketObjectListArgs } from "./bucketObjectList";
export type BucketObjectList = import("./bucketObjectList").BucketObjectList;
export const BucketObjectList: typeof import("./bucketObjectList").BucketObjectList = null as any;
utilities.lazyLoad(exports, ["BucketObjectList"], () => require("./bucketObjectList"));

export { BucketObjectPatchArgs } from "./bucketObjectPatch";
export type BucketObjectPatch = import("./bucketObjectPatch").BucketObjectPatch;
export const BucketObjectPatch: typeof import("./bucketObjectPatch").BucketObjectPatch = null as any;
utilities.lazyLoad(exports, ["BucketObjectPatch"], () => require("./bucketObjectPatch"));

export { BucketPatchArgs } from "./bucketPatch";
export type BucketPatch = import("./bucketPatch").BucketPatch;
export const BucketPatch: typeof import("./bucketPatch").BucketPatch = null as any;
utilities.lazyLoad(exports, ["BucketPatch"], () => require("./bucketPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:storage.gcp.upbound.io/v1beta2:Bucket":
                return new Bucket(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketIAMMember":
                return new BucketIAMMember(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketIAMMemberList":
                return new BucketIAMMemberList(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketIAMMemberPatch":
                return new BucketIAMMemberPatch(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketList":
                return new BucketList(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketObject":
                return new BucketObject(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketObjectList":
                return new BucketObjectList(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketObjectPatch":
                return new BucketObjectPatch(name, <any>undefined, { urn })
            case "kubernetes:storage.gcp.upbound.io/v1beta2:BucketPatch":
                return new BucketPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "storage.gcp.upbound.io/v1beta2", _module)
